name: local_platform
version: 1.0.0
config-version: 2
profile: local_platform

model-paths: ["models"]
seed-paths: ["seeds"]
clean-targets:
  - target
  - dbt_packages

models:
  local_platform:
    sdp:
      +database: "{{ env_var('SNOWFLAKE_SDP_DATABASE') }}"
      core:
        +schema: "{{ env_var('SNOWFLAKE_SDP_CORE_SCHEMA', 'CORE') }}"
        +materialized: view
      acc:
        +schema: "{{ env_var('SNOWFLAKE_SDP_ACC_SCHEMA', 'ACC') }}"
        +materialized: view
    edp:
      in:
        +database: "{{ env_var('SNOWFLAKE_EDP_DATABASE') }}"
        +schema: "{{ env_var('SNOWFLAKE_EDP_IN_SCHEMA', 'IN') }}"
        +materialized: view
      core:
        +database: "{{ env_var('SNOWFLAKE_EDP_DATABASE') }}"
        +schema: "{{ env_var('SNOWFLAKE_EDP_CORE_SCHEMA', 'CORE') }}"
        +materialized: table
      acc:
        +database: "{{ env_var('SNOWFLAKE_EDP_DATABASE') }}"
        +schema: "{{ env_var('SNOWFLAKE_EDP_ACC_SCHEMA', 'ACC') }}"
        +materialized: materialized_view
