version: 2

sources:
  - name: lakehouse
    database: "{{ env_var('SNOWFLAKE_RAW_DATABASE') }}"
    schema: "{{ env_var('ICEBERG_NAMESPACE', 'landing') }}"
    tables:
      - name: raw_orders
      - name: raw_order_items

models:
  - name: stg_raw_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: order_total
        tests:
          - not_null
  - name: fct_order_revenue
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

