version: 2

sources:
  - name: source_edp_orders_sdp_access
    database: "{{ env_var('SNOWFLAKE_SDP_DATABASE') }}"
    schema: "{{ env_var('SNOWFLAKE_SDP_ACC_SCHEMA', 'ACCESS') }}"
    tables:
      - name: T_ORDERS_ORDER_GRAIN
      - name: T_ORDERS_CUSTOMER_GRAIN
      - name: T_ORDER_LINES_ORDER_GRAIN

models:
  - name: model_edp_orders_core_dim_customers
    columns:
      - name: customer_sk
        tests:
          - not_null
          - unique
  - name: model_edp_orders_core_dim_order_status
    columns:
      - name: status_sk
        tests:
          - not_null
          - unique
  - name: model_edp_orders_core_fct_order_revenue_star
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_sk
        tests:
          - not_null
      - name: status_sk
        tests:
          - not_null
