version: 2

models:
  - name: model_edp_orders_core_dim_customers
    columns:
      - name: customer_sk
        tests:
          - not_null
          - unique
  - name: model_edp_orders_core_dim_order_status
    columns:
      - name: status_sk
        tests:
          - not_null
          - unique
  - name: model_edp_orders_core_fct_order_revenue_star
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_sk
        tests:
          - not_null
      - name: status_sk
        tests:
          - not_null
  - name: model_edp_orders_inbound_depot_transactions_grain
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique
  - name: model_edp_orders_core_depot_transactions_3nf
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique
  - name: model_edp_orders_access_depot_transactions_only
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique
