version: 2

models:
  - name: model_edp_orders_core_dim_customers
    columns:
      - name: customer_sk
        tests:
          - not_null
          - unique
  - name: model_edp_orders_core_dim_order_status
    columns:
      - name: status_sk
        tests:
          - not_null
          - unique
  - name: model_edp_orders_core_fct_order_revenue_star
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_sk
        tests:
          - not_null
      - name: status_sk
        tests:
          - not_null
