services:
  airflow-init:
    volumes: !reset []

  airflow-webserver:
    volumes: !reset []

  airflow-scheduler:
    volumes: !override
      - airflow-logs:/opt/airflow/logs
      - ./airflow/dags:/opt/airflow/dags

  dlt-extractor:
    volumes: !reset []

  dbt-executor:
    volumes: !reset []
