services:
  airflow-init:
    volumes: !reset []

  airflow-webserver:
    volumes: !reset []

  airflow-scheduler:
    volumes: !override
      - airflow-logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock

  dlt-extractor:
    volumes: !reset []

  dbt-executor:
    volumes: !reset []
