services:
  airflow-metadata-db:
    build:
      context: .
      dockerfile: postgres/catalog/Dockerfile
    image: ${COMPOSE_PROJECT_NAME:-local-platform}/airflow-metadata-db:dev
    volumes: !reset []

  source-postgres-db:
    build:
      context: .
      dockerfile: postgres/source/Dockerfile
    image: ${COMPOSE_PROJECT_NAME:-local-platform}/source-postgres-db:dev
    volumes: !reset []

  lakehouse-bucket-init:
    entrypoint:
      - /bin/sh
      - -ec
      - |
        until mc alias set local "${MINIO_ENDPOINT}" "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}"; do
          echo "waiting for MinIO"
          sleep 3
        done
        mc mb --ignore-existing "local/${MINIO_BUCKET}"
    volumes: !reset []

  airflow-init:
    volumes: !reset []

  airflow-webserver:
    volumes: !reset []

  airflow-scheduler:
    volumes: !override
      - airflow-logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock

  dlt-extractor:
    volumes: !reset []

  dbt-executor:
    volumes: !reset []
