name: ${COMPOSE_PROJECT_NAME:-proj-edp-local}

x-common-env: &common-env
  PLATFORM_DOCKER_NETWORK: ${PLATFORM_DOCKER_NETWORK:-local-platform-net}
  AWS_ACCESS_KEY_ID: ${OBJECT_STORE_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${OBJECT_STORE_SECRET_ACCESS_KEY}
  AWS_DEFAULT_REGION: ${OBJECT_STORE_REGION}
  AWS_REGION: ${OBJECT_STORE_REGION}
  MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  MINIO_BUCKET: ${MINIO_BUCKET}
  MINIO_MANIFEST_BUCKET: ${MINIO_MANIFEST_BUCKET:-dbt-manifests}
  MINIO_PREFIX: ${MINIO_PREFIX}
  MINIO_ENDPOINT: ${MINIO_ENDPOINT}
  MINIO_PUBLIC_ENDPOINT: ${MINIO_PUBLIC_ENDPOINT}
  MINIO_USE_SSL: ${MINIO_USE_SSL}
  MINIO_REGION: ${MINIO_REGION}
  OBJECT_STORE_TYPE: ${OBJECT_STORE_TYPE}
  OBJECT_STORE_BUCKET: ${OBJECT_STORE_BUCKET}
  OBJECT_STORE_ACCESS_KEY_ID: ${OBJECT_STORE_ACCESS_KEY_ID}
  OBJECT_STORE_SECRET_ACCESS_KEY: ${OBJECT_STORE_SECRET_ACCESS_KEY}
  OBJECT_STORE_ENDPOINT_URL: ${OBJECT_STORE_ENDPOINT_URL}
  OBJECT_STORE_REGION: ${OBJECT_STORE_REGION}
  OBJECT_STORE_USE_SSL: ${OBJECT_STORE_USE_SSL}
  SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
  SNOWFLAKE_USER: ${SNOWFLAKE_USER}
  SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
  SNOWFLAKE_ROLE: ${SNOWFLAKE_ROLE}
  SNOWFLAKE_WAREHOUSE: ${SNOWFLAKE_WAREHOUSE}
  SNOWFLAKE_CONTROL_DATABASE: ${SNOWFLAKE_CONTROL_DATABASE:-LOCAL_PLATFORM_CONTROL}
  SNOWFLAKE_CONTROL_SCHEMA: ${SNOWFLAKE_CONTROL_SCHEMA:-OPERATIONS}
  SNOWFLAKE_DBT_STAGE: ${SNOWFLAKE_DBT_STAGE:-DBT_PROJECT_STAGE}
  SNOWFLAKE_SDP_DATABASE: ${SNOWFLAKE_SDP_DATABASE}
  SNOWFLAKE_SDP_CUSTOMERS_DATABASE: ${SNOWFLAKE_SDP_CUSTOMERS_DATABASE}
  SNOWFLAKE_SDP_IN_SCHEMA: ${SNOWFLAKE_SDP_IN_SCHEMA}
  SNOWFLAKE_SDP_CORE_SCHEMA: ${SNOWFLAKE_SDP_CORE_SCHEMA}
  SNOWFLAKE_SDP_ACC_SCHEMA: ${SNOWFLAKE_SDP_ACC_SCHEMA}
  SNOWFLAKE_SDP_DBT_PROJECT: ${SNOWFLAKE_SDP_DBT_PROJECT:-DEV_DBT_PROJECT_SOURCE_FINNOVA}
  SNOWFLAKE_EDP_DATABASE: ${SNOWFLAKE_EDP_DATABASE}
  SNOWFLAKE_EDP_CUSTOMERS_DATABASE: ${SNOWFLAKE_EDP_CUSTOMERS_DATABASE}
  SNOWFLAKE_EDP_IN_SCHEMA: ${SNOWFLAKE_EDP_IN_SCHEMA}
  SNOWFLAKE_EDP_CORE_SCHEMA: ${SNOWFLAKE_EDP_CORE_SCHEMA}
  SNOWFLAKE_EDP_ACC_SCHEMA: ${SNOWFLAKE_EDP_ACC_SCHEMA}
  SNOWFLAKE_EDP_DBT_PROJECT: ${SNOWFLAKE_EDP_DBT_PROJECT:-DEV_DBT_PROJECT_EDP_ORDERS}
  SNOWFLAKE_EDP_CUSTOMERS_DBT_PROJECT: ${SNOWFLAKE_EDP_CUSTOMERS_DBT_PROJECT:-DEV_DBT_PROJECT_EDP_CUSTOMERS}
  SNOWFLAKE_CLONE_SCHEMA: ${SNOWFLAKE_CLONE_SCHEMA}
  SNOW_DBT_TARGET_NAME: ${SNOW_DBT_TARGET_NAME:-dev}
  DBT_THREADS: ${DBT_THREADS}

services:
  dbt-executor:
    build:
      context: .
      dockerfile: dbt/Dockerfile
    image: ${RUNTIME_IMAGE_PREFIX:-${COMPOSE_PROJECT_NAME:-proj-edp-local}}/dbt-executor:dev
    environment: *common-env
    volumes:
      - ./dbt:/opt/platform/dbt
      - ./ci/snowflake:/opt/platform/ci/snowflake
    networks:
      - platform

networks:
  platform:
    name: ${PLATFORM_DOCKER_NETWORK:-local-platform-net}
