name: proj_source_finnova
version: 1.0.0
config-version: 2
profile: local_platform

model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - target
  - dbt_packages

models:
  proj_source_finnova:
    orders:
      core:
        +database: "{{ env_var('SNOWFLAKE_SDP_DATABASE') }}"
        +schema: "{{ env_var('SNOWFLAKE_SDP_CORE_SCHEMA', 'CORE') }}"
        +materialized: table
      access:
        +database: "{{ env_var('SNOWFLAKE_SDP_DATABASE') }}"
        +schema: "{{ env_var('SNOWFLAKE_SDP_ACC_SCHEMA', 'ACCESS') }}"
        +materialized: table
        +access: public
    customers:
      core:
        +database: "{{ env_var('SNOWFLAKE_SDP_CUSTOMERS_DATABASE') }}"
        +schema: "{{ env_var('SNOWFLAKE_SDP_CORE_SCHEMA', 'CORE') }}"
        +materialized: table
      access:
        +database: "{{ env_var('SNOWFLAKE_SDP_CUSTOMERS_DATABASE') }}"
        +schema: "{{ env_var('SNOWFLAKE_SDP_ACC_SCHEMA', 'ACCESS') }}"
        +materialized: table
        +access: public
    taxes:
      core:
        +database: "{{ env_var('SNOWFLAKE_SDP_TAXES_DATABASE') }}"
        +schema: "{{ env_var('SNOWFLAKE_SDP_CORE_SCHEMA', 'CORE') }}"
        +materialized: table
      access:
        +database: "{{ env_var('SNOWFLAKE_SDP_TAXES_DATABASE') }}"
        +schema: "{{ env_var('SNOWFLAKE_SDP_ACC_SCHEMA', 'ACCESS') }}"
        +materialized: table
        +access: public
    depot_transactions:
      core:
        +database: "{{ env_var('SNOWFLAKE_SDP_DEPOT_TRANSACTIONS_DATABASE') }}"
        +schema: "{{ env_var('SNOWFLAKE_SDP_CORE_SCHEMA', 'CORE') }}"
        +materialized: table
      access:
        +database: "{{ env_var('SNOWFLAKE_SDP_DEPOT_TRANSACTIONS_DATABASE') }}"
        +schema: "{{ env_var('SNOWFLAKE_SDP_ACC_SCHEMA', 'ACCESS') }}"
        +materialized: table
        +access: public
