name: proj_domain_customer
version: 1.0.0
config-version: 2
profile: local_platform

model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - target
  - dbt_packages

models:
  proj_domain_customer:
    inbound:
      +database: "{{ env_var('SNOWFLAKE_EDP_CUSTOMERS_DATABASE') }}"
      +schema: "{{ env_var('SNOWFLAKE_EDP_IN_SCHEMA', 'INBOUND') }}"
      +materialized: view
    core:
      +database: "{{ env_var('SNOWFLAKE_EDP_CUSTOMERS_DATABASE') }}"
      +schema: "{{ env_var('SNOWFLAKE_EDP_CORE_SCHEMA', 'CORE') }}"
      +materialized: table
    access:
      +database: "{{ env_var('SNOWFLAKE_EDP_CUSTOMERS_DATABASE') }}"
      +schema: "{{ env_var('SNOWFLAKE_EDP_ACC_SCHEMA', 'ACCESS') }}"
      +materialized: table
