version: 2

models:
  - name: model_edp_customers_core_dim_regions
    columns:
      - name: region_sk
        tests:
          - not_null
          - unique
  - name: model_edp_customers_core_dim_segments
    columns:
      - name: segment_sk
        tests:
          - not_null
          - unique
  - name: model_edp_customers_core_fct_customer_value_star
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: region_sk
        tests:
          - not_null
      - name: segment_sk
        tests:
          - not_null
