use role ${SNOWFLAKE_ROLE};
use warehouse ${SNOWFLAKE_WAREHOUSE};

create or replace transient schema ${SNOWFLAKE_TARGET_DATABASE}.${SNOWFLAKE_CLONE_SCHEMA}
  clone ${SNOWFLAKE_TARGET_DATABASE}.${SNOWFLAKE_TARGET_SCHEMA};

show tables in schema ${SNOWFLAKE_TARGET_DATABASE}.${SNOWFLAKE_CLONE_SCHEMA};

drop schema if exists ${SNOWFLAKE_TARGET_DATABASE}.${SNOWFLAKE_CLONE_SCHEMA};

